dataset:
  base_dir: "/data/bvelghe/capstone2022/"
  train: ["B", "C"]
  test: ["A"]
  delta: 0.2
  dgcnn:
    dataset: "/data/bvelghe/capstone2022/C/2018E.EOSlist.CTRL_patched.h5"
    sample_file: "/fast_scratch_1/capstone_2022/datasetC_combined.h5"
    val: 0.05
    test: 0.05

data_loader:
  batch_size: 32
  num_workers: 4
  drop_last: True

model:
  pointnet:
    num_classes: 3
    epochs: 4
    class_weights:
    saved_model: "saved_models/pointnet_class_weight.pt"
    predictions: "saved_models/predictions_class_weight.csv"
  dgcnn:
    num_classes: 2
    epochs: 4
    k: 16
    output_channels: 1
    saved_model: "saved_models/test_dgcnn_2.pt"
    predictions: "saved_models/dgcnn_predictions_v3_binary_validation.csv"
    momentum: False
    radius: False

gpu:
  - 4
  - 5
  - 6 

seed: 42