dataset:
  delta: 0.5
  train:
    /data/bvelghe/capstone2022/B/2018B.Sample.EOSlist.CTRL.p.v2.0.4_f.v2.0.4_patched.h5: /fast_scratch_1/capstone_2022/combined_datasets/B.2018B.h5
    /data/bvelghe/capstone2022/C/2018E.EOSlist.CTRL_patched.h5: /fast_scratch_1/capstone_2022/datasetC_combined.h5
  test:
    /data/bvelghe/capstone2022/A/Run008548.EOSlist.CTRL.p.v2.0.4-01_f.v2.0.4-01_patched.h5: /fast_scratch_1/capstone_2022/combined_datasets/A.Run008548.h5
    /data/bvelghe/capstone2022/A/Run008553.EOSlist.CTRL.p.v2.0.4-01_f.v2.0.4-01_patched.h5: /fast_scratch_1/capstone_2022/combined_datasets/A.Run008553.h5
    /data/bvelghe/capstone2022/A/Run008562.EOSlist.CTRL.p.v2.0.4-01_f.v2.0.4-01_patched.h5: /fast_scratch_1/capstone_2022/combined_datasets/A.Run008562.h5
    /data/bvelghe/capstone2022/A/Run008563.EOSlist.CTRL.p.v2.0.4-01_f.v2.0.4-01_patched.h5: /fast_scratch_1/capstone_2022/combined_datasets/A.Run008563.h5
    /data/bvelghe/capstone2022/A/Run008564.EOSlist.CTRL.p.v2.0.4-01_f.v2.0.4-01_patched.h5: /fast_scratch_1/capstone_2022/combined_datasets/A.Run008564.h5
  dgcnn:
    val: 0.05
    test: 0.05
  pointnet:
    val: 0.05
    test: 0.05
  centre_bias:
    mean_x: -110.25
    mean_y: 1.14
  standardize:
    mean_momentum: 31.338661
    std_momentum: 7.523443
    mean_radius: 174.97235
    std_radius: 12.013085
  filters:
    momentum_lower: 15
    momentum_upper: 45
    radius_lower: -2500
    radius_upper: 2500
data_loader:
  batch_size: 64
  num_workers: 4
  drop_last: true
model:
  pointnet:
    output_channels: 1
    epochs: 16
    saved_model: saved_models/pointnet.pt
    predictions: saved_models/pointnet_predictions.csv
    train_result: saved_models/train_result_pointnet.csv
    momentum: true
    radius: true
    seed: 2022
    learning_rate: 0.0003
  dgcnn:
    output_channels: 1
    epochs: 4
    k: 8
    saved_model: saved_models/dgcnn.pt
    predictions: saved_models/dgcnn_predictions.csv
    train_result: saved_models/train_result_dgcnn.csv
    momentum: true
    radius: true
    seed: 42
    learning_rate: 0.0003
gpu:
  - 1
  - 2
  - 3
