dataset:
  base_dir: "/data/bvelghe/capstone2022/"
  train: ["B", "C"]
  test: ["A"]
  dgcnn:
#     dataset: "/data/bvelghe/capstone2022/A/Run008553.EOSlist.CTRL.p.v2.0.4-01_f.v2.0.4-01.h5"
    dataset: "/data/bvelghe/capstone2022/C/2018E.EOSlist.CTRL_patched.h5"
    val: 0.1
    test: 0.1

data_loader:
  batch_size: 32
  num_workers: 2

model:
  pointnet:
    num_classes: 3
    epochs: 4
    class_weights:
    saved_model: "saved_models/pointnet_class_weight.pt"
    predictions: "saved_models/predictions_class_weight.csv"
  dgcnn:
    num_classes: 3
    epochs: 1
    k: 16
    saved_model: "saved_models/dgcnn.pt"

gpu:
  - 4
  - 5

seed: 42