dataset:
  base_dir: "/data/bvelghe/capstone2022/"
  train: ["B", "C"]
  test: ["A"]

data_loader:
  batch_size: 64
  num_workers: 8  

model:
  pointnet:
    num_classes: 3
    epochs: 5
    saved_model: "saved_models/pointnet_2.pt"
    predictions: "saved_models/predictions_2.csv"

gpu:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 7