title: RICH AI Final Report
author: Nico Van den Hooff, Rakesh Pandey, Mukund Iyer, Shiva Jena
copyright: "2022"
logo: assets/TRIUMF_Logo_Blue.jpeg

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/TRIUMF-Capstone2022/richai
#   path_to_book: docs  # Optional path to your book, relative to the repository root
#   branch: master  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: true
  favicon: "assets/TRIUMF_Favicon.png"

sphinx:
  config:
    bibtex_reference_style: author_year

parse:
  myst_enable_extensions:
    - html_image

execute:
  execute_notebooks: 'off'