name: deploy-book

on:
  push:
    branches:
    - master
    paths:
    - ./docs/final_report/
  workflow_dispatch:

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -U jupyter-book

    - name: Build the book
      run: |
        jupyter-book build --all docs/final_report/

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/final_report/_build/html
